### ISSUE TITLE
[QA] FAQ Accordion Not Triggering on Graphic

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#10]
**Desktop & Mobile**
Link: https://pointlesscorp.netlify.app/
Browser: Chrome Latest, Safari Latest

**Details**
On the live site, you can click the plus or minus and it will activate the accordion. On staging, only the title will activate the accordion. 

[Pointless Corp - The Innovation Lab at Viget - 21 November 2024 - Watch Video](https://www.loom.com/share/d68552e0963a460f975d8b6f8d2089a0)

**Comment by ten1seven** [comment]
@arielkidwell updated!
