### ISSUE TITLE
[QA] Hero Headline Centered

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#11]
**Mobile**
Link: https://pointlesscorp.netlify.app/#contact
Browser: Chrome iOS

**Details**
The headline in the hero is centered on the staging site (vs. left aligned on current one).

![Image](https://github.com/user-attachments/assets/203cd7a9-32e3-4437-b6d1-ab3a74bab096)

**Comment by ten1seven** [comment]
@arielkidwell This was a choice to align it with the centered logo, but meh, I'm not attached to it so I moved it back to left-aligned.
