### ISSUE TITLE
[QA] Broken Accordion Formatting

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#12]
**Mobile**
Link: https://pointlesscorp.netlify.app/
Browser: Chrome iOS

**Details**
![IMG_0406](https://github.com/user-attachments/assets/3145aaca-6c63-4a3e-92f7-3788395d3cf7)
![IMG_0407](https://github.com/user-attachments/assets/2ca02350-975a-4915-b5ab-1bcaccbcf732)

**Comment by ten1seven** [comment]
@arielkidwell fixed!
