### ISSUE TITLE
[QA] Photo collage doesn't stack

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#13]
**Mobile**
Link: https://pointlesscorp.netlify.app/
Browser: Chrome iOS

**Details**
On current site these stack one at a time - likely to allow hovers to be legible?

![IMG_0408](https://github.com/user-attachments/assets/efd2ee1a-5843-4384-8b03-d454e221e865)

**Comment by ten1seven** [comment]
@arielkidwell this was a choice on my part to reduce the overall page height from so many images stacking.
