### ISSUE TITLE
[QA] Project Detail Page: Table Bleeds to RIght

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#14]
**Mobile**
Link: https://pointlesscorp.netlify.app/pow-wow/ and https://pointlesscorp.netlify.app/starbnb/
Browser: Chrome iOS

**Details**
Visually
- Tables bleed off right side

Functionally
- User is able to swipe to the right and break the page

![Image](https://github.com/user-attachments/assets/77d4d9eb-0f2d-4c9a-9573-5fe70890511a)
![Image](https://github.com/user-attachments/assets/c16ac8c4-22e8-4911-85d3-49de7060c937)

**Comment by ten1seven** [comment]
I missed this when doing the responsive build. The existing table stacks on smaller screens so I'm gonna go with that.

![Image](https://github.com/user-attachments/assets/aa9912e0-5216-4d6c-a858-4fa4aa1ccf71)

**Comment by ten1seven** [comment]
@arielkidwell I went with a combo solution to stack the table on small screens like the current implementation but to also allow side scrolling for tables that happen to be wider than the breakpoint where it stacks. This is ready to test https://pointlesscorp.netlify.app/storyboard/

![Image](https://github.com/user-attachments/assets/e74a58c7-9444-42f6-829d-39cabfc6076e)
