### ISSUE TITLE
[WCAG] Project Listing: Graba Project Flagged for Contrast

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#18]
**Details**
![Image](https://github.com/user-attachments/assets/8e9d220b-3ae3-41b3-8663-a314bbf2ab66)

**Comment by ten1seven** [comment]
@arielkidwell when I ran this the Grabba card passed 🤷 

![Image](https://github.com/user-attachments/assets/98486d1a-349e-448b-b824-d7ceeac45dfa)

**Comment by arielkidwell** [comment]
@ten1seven That was after I changed it 😆
