### ISSUE TITLE
[WCAG] Low Contrast Flagged on Image Caption

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#19]
**Details**
![Image](https://github.com/user-attachments/assets/477cab00-09d2-465f-837d-1ce8caa0828f)

**Comment by ten1seven** [comment]
@arielkidwell the contrast checker can't "see" images, so it checks the text against the background color. In this case it's white on white  which results in that 1:1 ratio. In cases like this you can make a judgement call and spot check the photo colors (I'm using https://webaim.org/resources/contrastchecker/) and disregard the warning if you can verify that it passes. This photo is plenty dark in the bottom corner so I think it's okay to not flag it.

![Image](https://github.com/user-attachments/assets/61510adc-3989-4b47-80b3-84c79fc6b1ce)

**Comment by arielkidwell** [comment]
Thank you for noting this for me @ten1seven ! Definitely noted for future testing.
