### ISSUE TITLE
[QA] Image Banner Missing Avatar

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#8]
**Desktop**
Link: https://pointlesscorp.netlify.app/
Browser: Chrome Latest, Safari Latest

**Details**
See missing avatar (picture in circle) next to "Trevor leads..." caption

**Live**
![Image](https://github.com/user-attachments/assets/4ddbd90b-5c97-4cdc-b4be-b3d7f400328e)

**Staging**
![Image](https://github.com/user-attachments/assets/967e01b0-09ec-4b91-a82e-b106f31a181e)

**Comment by carolynhack** [comment]
@ten1seven mentioned that this was on purpose for simplification, since a lot of the avatars were for Viget alums, who no longer have pages on the site to link to.

**Comment by arielkidwell** [comment]
@carolynhack Thank you! I think there might be a couple like that. He pointed out that some adjustments had been made.
