### ISSUE TITLE
[QA] Missing Avatars on Hover in Image Collage

### ISSUE THREAD

**Issue by arielkidwell** [vigetlabs/pointless-corp-astro#9]
**Desktop**
Link: https://pointlesscorp.netlify.app/
Browser: Chrome, Safari latest

**Details**
The photo collage is missing the avators on the hover states.

Related: https://github.com/vigetlabs/pointless-corp-astro/issues/8

![Image](https://github.com/user-attachments/assets/28182036-ab08-4131-9630-5c847cebccc4)

**Comment by carolynhack** [comment]
@ten1seven mentioned that this was on purpose for simplification, since a lot of the avatars were for Viget alums, who no longer have pages on the site to link to.
